### ISSUE TITLE
Game loop under a React Component

### ISSUE THREAD

**Issue by Tilican** [Izzimach/react-pixi#102]
Hi,

I use your lib for a school protoype, but i have a little problem cause i want the delta time since 2 render in the canvas, how i can do that ?

I use es6 / react 15.6.1 cause react 16 doesn't work with this lib

thx 👍

**Comment by Izzimach** [comment]
You can ovverirde the `render` method in the stage, could you use this to keep track of the time using `performance.now()` or something similar?

**Comment by michalochman** [comment]
@Tilican @Izzimach FYI I have just released [michalochman/react-pixi-fiber](https://github.com/michalochman/react-pixi-fiber) that works with React 16.

**Comment by Izzimach** [comment]
Nice, I'll add something to the README
