### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by weepy** [Izzimach/react-pixi#12]
heya - you mentioned that they're not supported, but can filters be handled manually ?

**Comment by Izzimach** [comment]
Right now if you pass in `filters` and/or `filterArea` as props they just get passed on to the Sprite without any filtering or munging. So try that and see if it works. If you can't get that to work post some and I can see if something in react-pixi is broken.

**Comment by weepy** [comment]
ok I'll give it go !

**Comment by Izzimach** [comment]
@weepy let me know if you try this and it works/doesn't work. If filters do work, maybe I could take some snippets of your code to make an example.

**Comment by weepy** [comment]
ok ...  it might be a little while till I get a chance FYI. J

**Comment by mattrei** [comment]
any chance we might get this working? 
thanks.

**Comment by Izzimach** [comment]
I haven't checked this yet, did you try something that was broken? I'll try to write up a test for this.

**Comment by Izzimach** [comment]
Looks like the filters are working. I added a filter example here which applies blur: 83766d402e696b4b33fd3c32a9f63774c0df1a35

Screenshot is here: https://github.com/Izzimach/react-pixi/blob/master/docs/blurexample.png
