### ISSUE TITLE
Contexts - warning when crossing into ReactPIXI components.

### ISSUE THREAD

**Issue by netikular** [Izzimach/react-pixi#15]
I'm trying to use contexts in my application, and I'm finding that it is not working as expected.

The contexts come through just fine with the normal react classes that I'm creating, however as soon as I cross in to the react-pixi classes i lose the parent context, I've tried to make sense of the ReactContext stuff, but thought I would ask here if anyone else has run into the issue.  I basically just want to make sure that the warning I'm getting is ok to ignore and I won't get stuck when react 0.14.0 comes out :smile: 

```jsx
<div className="main-view">
  <Stage width={1024} height={768} backgroundcolor={0xFFFFFF} >
    <Background label={this.props.floor} zoom={this.props.zoom}/>
  </Stage>
</div>
```

Background looses the context some where.

**Comment by Izzimach** [comment]
The underlying plumbing should be the same, so not sure why the context wouldn't get passed down.

You're just using `getchildContext` in a parent component and it doesn't show up in anything below the `Stage`?

**Comment by Izzimach** [comment]
Looks like when children are mounted they are given an empty context:

https://github.com/Izzimach/react-pixi/blob/master/src/ReactPIXI.js#L237

So this code needs to figure out the current context and pass that down instead.

**Comment by Izzimach** [comment]
Hm, some conflicts between parent context and owner context. Some references:

https://github.com/facebook/react/issues/2112
https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7
https://github.com/facebook/react/issues/3451

React 0.14 will switch to parent-based context, so those warnings might be a problem. Need a test case or two to make sure nothing breaks down the road.

**Comment by Izzimach** [comment]
This appears to work for now. It's a bit ugly and will probably have to be re-visited for React 0.14

 @netikular please re-open if you still have problems with contexts.
