### ISSUE TITLE
Update to React 0.14

### ISSUE THREAD

**Issue by Izzimach** [Izzimach/react-pixi#16]
See [the issue in react-three](https://github.com/Izzimach/react-three/issues/24) for more details. In summary:

1. update to React 0.14
2. remove DOM reference where possible
3. figure out how to make react-pixi and react-three target native OpenGL.

**Comment by nickdima** [comment]
What do you think about no. 3? Would be cool to have this working with OpenGL in React Native.
Do you have any ideas yet about how could this work?

**Comment by quicksnap** [comment]
Would it take much work to upgrade to 0.14 similar to https://github.com/Izzimach/react-three/commit/b8f8ce1faee5eca52066e345f58a63827f924a9c ?

I have been toying with the react-pixi idea, so I might have time to try a version bump soon, if you'd accept a PR.

**Comment by Izzimach** [comment]
I think react-pixi would require pretty much the same changes as
react-three did, so not much work at all.

If you fix up react-pixi so that it passes all the tests with 0.14-rc1 I'll
take the PR.  However I don't want to push a new `npm` version that uses a
release candidate of react, so it won't get published onto npmjs until 0.14
is officially released. You can always run it from the git repo of course.

**Comment by quicksnap** [comment]
Awesome! I'll hopefully have some time soon.

**Comment by tracker1** [comment]
Looks like [0.14 is released](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html) now.

**Comment by quicksnap** [comment]
:tada: :tada: :tada: :tada:

**Comment by Izzimach** [comment]
kk, let me finish fixing up react-three for 0.14 and I'll get react-pixi patched up next.

**Comment by Izzimach** [comment]
dev branch works with React 0.14: f46504387d68dc8480a126ff43147c85ded2cd6e
Try it out, if it breaks please post here.

I'll publish to npm in a few days prolly.

**Comment by quicksnap** [comment]
Thanks!

**Comment by Izzimach** [comment]
0.7.0 was broke. 0.7.1 is published.
