### ISSUE TITLE
Working with React DevTools

### ISSUE THREAD

**Issue by fsbdev** [Izzimach/react-pixi#19]
This is just a question. I'm integrating React with a WebGL engine that has a scene graph, and have things rendering on screen but when using the chrome extension to examine the component tree, all I see displayed under my Surface (Stage-equivalent component) in the tree list is the canvas element. Do you know of any specific properties that need to be added for the chrome extension to pick things up correctly? Thanks

**Comment by Izzimach** [comment]
Sorry, I don't know offhand what you need to add to your component to get them to show in dev-tools. I imagine it's one of the internal data members that start with an underscore, and probably change with each version. You can look at [react-art](https://github.com/reactjs/react-art] which is usually kept up-to-date with the current version of React, and see which internal data members are used there.
