### ISSUE TITLE
Events system

### ISSUE THREAD

**Issue by fabienbrooke** [Izzimach/react-pixi#20]
More of a question - you say the events don't feed into React's event system but isn't that system just for DOM events and the nature of them, React wants to autodelegate to the root and let them all bubble there? Do PIXI events bubble? I'm wondering what the benefit of putting them in that system would be. Custom events in React are just use single listener "callbacks" like you said.

**Comment by Izzimach** [comment]
That's mostly a clarification. With the React events, you can inject your own events and do some other fancy tricks. With react-pixi events are just callbacks: you provide a function to call every time a click event (or whatever) occurs and you can't take advantage of React's event system. Usually this isn't a big deal so I haven't bothered "fixing" it.

**Comment by fsbdev** [comment]
What would you get by taking advantage of it I guess is what I was wondering. I thought it was just to accommodate the nature of DOM events.

**Comment by Izzimach** [comment]
You could filter/consume events or inject your own for testing. Prolly some other uses but I've not done much with it.

**Comment by fsbdev** [comment]
How would one inject their own events into React's system?

**Comment by Izzimach** [comment]
I haven't actually done that :(

Look at `react/lib/EventPluginHub.js` to start. You will have probably have to find some projects on Github that inject custom events and see how they do it.

**Comment by fsbdev** [comment]
I did a little investigation and asked for some suggestions on ReactART, but they said it's not supported. https://github.com/reactjs/react-art/issues/67
Will keep looking at a way to do it though. I couldn't find any other project injecting and dispatching custom events yet.
