### ISSUE TITLE
Can not render ReactPIXI component inside ReactRouter handler 

### ISSUE THREAD

**Issue by therealthing** [Izzimach/react-pixi#28]
I'm using ReactRouter with Flux and ReactPIXI. 
I started by forking the following repo: https://github.com/jaketrent/demo-react-router-flux and I'm trying to display a stage/container inside a route-handler component (file: books/show.js in our case).

I get the following error message, even though the ReactPIXI component is valid: 
 
<img width="336" alt="screenshot at nov 10 11-16-38" src="https://cloud.githubusercontent.com/assets/3314572/11058606/a53e7ae6-879c-11e5-84b1-fa88905e3f4a.png">

**Comment by Izzimach** [comment]
Man, I have not used ReactRouter so I dunno what sort of strange interaction might be happening there. If you render the Stage outside the route container it works fine?

If you make a branch in your repo with the bug I can clone it and try to figure out what is happening.

**Comment by therealthing** [comment]
With the help of one of ReactRouter's contributors I solved it. I can propose an example (if you consider it helpful for others who might get into the same problem: mixing ReactRouter with ReactPIXI).

**Comment by Izzimach** [comment]
Yeah, if you have a short example that would be great. I imagine this will not be the only time someone tries to use ReactPIXI with React-Router
