### ISSUE TITLE
masking

### ISSUE THREAD

**Issue by batm4n** [Izzimach/react-pixi#32]
Is there a way to apply a mask for nested components, or a masking implementation in general? A custom react PIXI component example perhaps?

Something like:
```
<GraphicPrimitive mask={true}>
  <Sprite image="/img/bear.png" />
</GraphicPrimitive>
```

Native implementation in [PIXI examples](http://pixijs.github.io/examples/index.html?s=demos&f=masking.js&title=Masking)

**Comment by Izzimach** [comment]
`mask` is already listed as a standard prop, so if you don't mind creating and updating your own `PIXI.Graphics` you can pass that in as the `mask` prop and it should work similar to the example.

As for rendering the mask with React components...well, I suppose `mask` could also be a string or name of some child object that would be used as the mask. Supporting all the graphics commands available in the `Graphics` object would be a chunk of work though.
