### ISSUE TITLE
Catching PIXI events in React components

### ISSUE THREAD

**Issue by therealthing** [Izzimach/react-pixi#34]
**Thank you for your great work on ReactPIXI in the first place.**

I'm trying to catch an event triggered on a PIXI Sprite (clicking a tile for example) outside PIXI Stage, in the React component that renders the Stage. By catching this event, I can update the parent component/other React components.

I have the code below for the sprite object, 

`var home = {
        ...
        interactive:true,
        cursor: 'pointer',
        click: $.proxy(linkClick,this,i),
        touchstart: $.proxy(linkClick,this,i),
        mouseover: $.proxy(linkHover,this,i),
        key: '5home'+i+refnumber.toString()
      };`

and this for pushing sprites into DisplayObjectContainer. However, I don't know how can I pass a handler to Container, along with the sprites array.

`var appSprites = React.createClass({
  displayName:"DynamicSprites",
  propTypes: {
    sprites: React.PropTypes.arrayOf(React.PropTypes.object)
  },
  render: function() {
    var args = [{}];
    this.props.sprites.forEach(function(spriteprops) {
      args.push(Text(spriteprops));
     });
    return Container.apply(null,args);
  }
});`

Is there any way I can do this? Thanks!

**Comment by Izzimach** [comment]
Well, there is no easy way to do this without modifying the `DynamicSprites` component as it blindly passes sprite props down to the `Text` component.

If you want to use a single click handler for all sprites you'll have have to set `click` in every element of `sprites` before passing it into `DynamicSprites`. Alternately you could 'inject' the handler into each instance of `spriteprops` yourself: (not tested)

```
var appSprites = React.createClass({
  displayName:"DynamicSprites",
  propTypes: {
    sprites: React.PropTypes.arrayOf(React.PropTypes.object),
    globalclickhandler: React.PropTypes.func
  },
  render: function() { 
    var args = [{}];
    this.props.sprites.forEach(function(spriteprops) {
      var spritepropscopy = _.clone(spriteprops);
      spritepropscopy.click = globalclickhandler;
      args.push(Text(spritepropscopy));
    });
    return Container.apply(null,args); 
  }
});
```

**Comment by therealthing** [comment]
Thank you. 
I've just tested and it does catch the event from PIXI to my handler from React. However, looking through event InteractionData and event Target info, I cannot link the event to a particular sprite (except for position on screen at that moment). I was trying to find some id/class/custom property I passed to the sprite on drawing.

**Comment by Izzimach** [comment]
AFAIK pixi doesn't provide any of that info. You'll have to do something similar to the interactive test, which creates a closure for each sprite that takes specific info (the sprite ID) and passes that to some other function.
