### ISSUE TITLE
assetpath?

### ISSUE THREAD

**Issue by si13b** [Izzimach/react-pixi#35]
Hello,

The examples in the README include a reference to the function `assetpath`. However, there is no import or declaration of this function within the examples. I've checked the pixi.js website and npm, but could not find any documentation or a reference to a function of that name.

It would be great to see some elaboration or indication of what this is in the examples.

Thanks!

**Comment by Izzimach** [comment]
`assetpath` is just a function that points to wherever you put the assets.  I
think it appears in the examples near the top.

But it doesn't appear in the README, which yeah is confusing. Should
probably add that to the example in the README.
