### ISSUE TITLE
Loading SpriteSheet

### ISSUE THREAD

**Issue by ryansese** [Izzimach/react-pixi#37]
Been trying out react-pixi for awhile and so far I've been enjoying it alot. This is not an issue but more of an inquiry on how to use spritesheet with jsxtransform. Thanks in advance.

**Comment by Izzimach** [comment]
There really isn't an elegant way to use spritesheets with react-pixi unfortunately.

Looking at [this example](http://www.goodboydigital.com/pixijs/examples/2/) I suggest that you load the spritesheet yourself using a `PIXI.AssetLoader` and then extract the frames with `PIXI.Texture.fromFrame()`. At that point you should be able to use a frame as the `image` attribute for a `<Sprite>` component.

That SHOULD work although I haven't tried it. If you do get it to work, post in here or make a PR so I can add it to the examples.

**Comment by ryansese** [comment]
I'll definitely give a try, thanks
