### ISSUE TITLE
CreateCustomPIXIComponent

### ISSUE THREAD

**Issue by ryansese** [Izzimach/react-pixi#38]
Been looking ate the subclasssprite on you examples folder. And I noticed the the CreateCustomPIXIComponent does not exist anymore. Been trying to create a MovieClip component and is alittle bit stuck :). thanks again.

**Comment by Izzimach** [comment]
Hm, for some reason I decided to change `CreateCustomPIXIComponent` to `CustomPIXIComponent`. [as shown here[(https://github.com/Izzimach/react-pixi/blob/master/src/ReactPIXI.js#L685). Can you try changing the subclasssprite example to see if that works? If so, I can fix the example.

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 
"react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180" and 
"react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined"

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 
"react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180" and 
"react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined"

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 
"react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180" and 
"react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined"

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 
"react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180" and 
"react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined"

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 
"react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180" and 
"react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined"

**Comment by ryansese** [comment]
I did change it to CustomPIXIComponent, but now I'm getting an error 

react-pixi.js:2180 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactorywarning @ react-pixi.js:2180

react-pixi.js:15760 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined

**Comment by Izzimach** [comment]
Yeah, the spinningsprite example was never updated to use the changed API. I updated it in commit 086e7f6883db377c3cfdf28257ce56edbd372c2a
