### ISSUE TITLE
Sprite width / height settings

### ISSUE THREAD

**Issue by izeau** [Izzimach/react-pixi#40]
Hi, I’m using react-pixi for a toy project and so far I’ve been loving it! Thanks for making such a lib!

However, I’m having a difficult time scaling my images. In my game, I’ve got bosses that are bigger versions of monsters. I’m trying to scale the sprite, but unfortunately this doesn't seem to be working:

```jsx
/* Setting the width or height attributes doesn't have any effect */
<Sprite width={150} height={150} asset="/sprites/monster@2x.png" x={x} y={y} />
```

I’ve also tried using a texture and setting its `width` and `height` properties, to no avail.

Can you throw me a bone here? Am I missing something?

Cheers!

**Comment by Izzimach** [comment]
Oops, I don't think `width` and `height` are getting passed through to the `Sprite`. Until that's fixed, you can use the `scale` props instead.
