### ISSUE TITLE
Error when using version 0.8.0

### ISSUE THREAD

**Issue by LucianoGraziani** [Izzimach/react-pixi#42]
This version with react@15.0.0 or above throws two kind of errors:

- When start the app:

    > Warning: patching react to work with react-pixi

- On every `requestAnimationFrame`:

    > Warning: ReactDebugTool: debugID may not be empty.
    > Warning: exception thrown by devtool while handling onSetChildren: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().

The first happens always before loading react-pixi. The seccond only if <Stage> has children.

**Comment by Izzimach** [comment]
Thanks!

the 'patching react' is standard and will probably be in there until I get a better way to
hook into React's framework.

The second warning appears to have started with version 15.1.0. I guess they added in `_debugID` so the Stage will have to make sure it has that referenced.

**Comment by Izzimach** [comment]
Not sure where that third warning is coming from?

**Comment by LucianoGraziani** [comment]
It appears to be just one. I updated to v0.8.1 and both errors disappeared (2nd and 3rd). Thank you!
