### ISSUE TITLE
Access to the game loop

### ISSUE THREAD

**Issue by LucianoGraziani** [Izzimach/react-pixi#47]
Is it possible to access to the game loop? With a hook, for example. I want to add movement to a Sprite, but as I learned with https://github.com/kittykatattack/learningPixi#keyboard-movement, I need to add the velocity movement to the loop.

Thank you.

**Comment by Izzimach** [comment]
react-pixi doesn't really have a game loop, it just does the render part. You can make your own game loop with `requestAnimationFrame` and then call `ReactPIXI.render` every frame to re-draw. The interactive example does that [here](https://github.com/Izzimach/react-pixi/blob/master/examples/interactive/interactive.js#L145) but you can also put your game loop outside of the React components as well.
