### ISSUE TITLE
pixelDensityRatio support or how to style the canvas?

### ISSUE THREAD

**Issue by andrewluetgers** [Izzimach/react-pixi#49]
How can I pass style props to the canvas? I need to scale it down for retina. To get it to work I patched the PIXIStage render function like so

```
	  render: function render() {
	    // the PIXI renderer will get applied to this canvas element
	    var can = _react2.default.createElement("canvas", {style: this.props.style});
		  return can;
	  }
```

was then able to pass a width and height style that was 1/2 that passed to the stage thus getting a nice crisp retina canvas but, there seems to be support for props to be applied to the canvas howevr I was unable to get it to work without the above.

**Comment by Izzimach** [comment]
Yeah, supposedly all normal DOM props get passed onto the canvas but that's not well tested. So you just want the store prop forwarded to the canvas element?

**Comment by andrewluetgers** [comment]
I'm using JSX maybe that is the problem but in jsx when i do <Stage style={{width: "800px", height: "1000px"}} /> the style of the canvas was not getting updated.

**Comment by Izzimach** [comment]
OK, so as you said the `width` and `height` props dictate the WebGL resolution, while the `style` prop controls the actual size of the `<canvas>` element. If there is no `style` the canvas size defaults to whatever was set by the `width` and `height` props. So `style` should get passed into the `canvas` like you indicated above.
