### ISSUE TITLE
Not compatible with Pixi v4.0

### ISSUE THREAD

**Issue by ShayDavidson** [Izzimach/react-pixi#53]
There's a fork that upgraded the `peerDependency` (https://github.com/Prior99/react-pixi) but things are not rendered within a Stage component with Pixi v4.0.0.

**Comment by netikular** [comment]
@Izzimach what have you tried so far?

We are thinking about trying the upgrade in our app but don't want to duplicate work.

**Comment by Izzimach** [comment]
Did you manage to run it without errors? It appears that pixi.js needs to use `glslify` from browserify to transform some files. The default webpack setup doesn't do this. Dunno if that's the only problem though.

**Comment by ShayDavidson** [comment]
I used a the webpage `ify` loader without problems and managed to run it without errors. 
Creating a stage/canvas was easy, yet rendering things didn't do anything.

**Comment by Izzimach** [comment]
Hm, I checked the examples running under PIXI 4 and some work while others don't.

It appears that the `anchor` member now requires a `PIXI.ObservablePoint` in PIXI 4. Previous versions of PIXI used a `PIXI.Point` here.

@ShayDavidson can you check if your code uses anchor values? This might be the problem. In any case, there should be a check added to ReactPIXI code to warn people about using `PIXI.Point`

**Comment by ShayDavidson** [comment]
Yep, removing the anchor from the Sprite solved the problem.

I tried changing the `anchor` default to `ObservablePoint` but it didn't work as well:
https://github.com/ShayDavidson/react-pixi/commit/98629fb84fb8f67a7a0f2ec90f344215b3a6ea2a

**Comment by Izzimach** [comment]
Looking at the docs [here](https://pixijs.github.io/docs/PIXI.ObservablePoint.html) the `PIXI.ObservablePoint` constructor requires a callback and scope, so you can't just construct them willy-nilly. Typically you copy new data into them. So I probably should not have people passing `PIXI.ObservablePoint` in as props.

I guess what I'll do is have the `Sprite` component continue to take a `PIXI.Point` as the `anchor` and them internally copy the data over to the `anchor` so that PIXI is happy.

**Comment by Izzimach** [comment]
Ok, did some fixes and put them in the `pixi4` branch.

Look at [the pixi4 branch](https://github.com/Izzimach/react-pixi/tree/pixi4) and see if this works.

**Comment by ShayDavidson** [comment]
yes! thank you :) I'll update soon

**Comment by ShayDavidson** [comment]
@Izzimach it works - thank you!

**Comment by ShayDavidson** [comment]
@Izzimach found another problem:

Textures generated using `renderer.generateTexture(graphic)` (the pixi 4 way) do not show,
yet `graphic.generateTexture()` do.

**Comment by Izzimach** [comment]
Did you construct your own renderer then, and pass it into the `PIXIStage`?

I haven't used `generateTexture` before. A test would go something like this?

```javascript
var renderTexture = RenderTexture.create(100 ,100);
var renderer = PIXI.autoDetectRenderer(width,height);
renderer.render(mySprite, renderTexture);
```

and then pass `renderTexture` in as the texture for a Sprite component?

**Comment by ShayDavidson** [comment]
Okay, I found the problem:
I was not passing my `renderer` to the `Stage` component. 

I think it'd be awesome if some of the `generateDefaultRenderer` functionality would be passed to a renderer passed in the `props` (for example, backgroundColor and the view), otherwise I have to perform all sorts of hacks to make it work (setting the view on the renderer outside of the "react" scope)

**Comment by ShayDavidson** [comment]
Okay, I found the problem: I was not passing my renderer to the Stage component, hence I was rendering the texture with one renderer and ReactPixi was using the default renderer.

The problem I now face is that, assuming I use the `generateDefaultRenderer` renderer, i need to produce textures using it before I pass them to my sprites. From a design point of view I have trouble wrapping my head on where this should happen: 

- I can't pass the textures as context because `getChildContext` is initially called before `render` thus I don't have the renderer at that point.
- I can't pass the textures as props, because the renderer is created initially in the react tree, and i don't have any reference to it for other react components in the tree.
- I can try to create the renderer manually, memoize it, and then use the textures I create beforehand with context/globally, but ATM I am not fond of that solution because it means I have to put the `view` generated by my renderer in a hacky way in the DOM (something I get for free when using ReactPixi). ATM, ReactPixi doesn't seem to handle well that use case (maybe I'm missing something though).

**Comment by ShayDavidson** [comment]
@Izzimach btw, I'd be happy to help contributing to the project and solve these :)

**Comment by Izzimach** [comment]
OK, lemme make a separate issue for that though.

**Comment by nathantalewis** [comment]
@Izzimach, Any thoughts on when 0.9.0 might be pushed to npm?

**Comment by netikular** [comment]
@nathantalewis it is on npm.
