### ISSUE TITLE
react-pixi-commonjs.js:955 Warning:"patching react to work with react-pixi"

### ISSUE THREAD

**Issue by plftzk** [Izzimach/react-pixi#56]
Dear Izzimach:
    {
        ... ...
        "react": "^15.3.2",
        "pixi.js": "^4.0.3",
        "react-pixi": "^0.9.0",
        ... ...
    }
    When I use react-pixi, I can get a warning:"patching react to work with react-pixi".But the demo I write will run normally, found no problem.
    And I build the react pixi boilerplate  https://github.com/brigand/react-pixi-boilerplate, still have the warning.
    And I read the comment in "es5/react-pixi-commonjs.js", line number 2675 - 2685.But still didn't know how to fixed the warning.
    If I ignore this warning, what can be affected?
    thanks!!!

**Comment by Izzimach** [comment]
This is normal, it is in there since react-pixi changes some React internals and this can cause problems for some versions of React. If you don't see anything wrong it is OK to ignore this.

It might be good to make this a normal log message instead of a `warning` though, I suppose.

**Comment by plftzk** [comment]
Thank you very much!!!
