### ISSUE TITLE
react-pixi 0.9.0 doesn't include pixi.js

### ISSUE THREAD

**Issue by dankreek** [Izzimach/react-pixi#57]
Hello! In the README it's mentioned that _react-pixi_ includes both _react_ and _pixi.js_ but I've found this to not be true. Has this changed recently? 

I ask because I'm building a React app from the group up using their `create-react-app` tool. I had to manually install _pixi.js_ by doing:

```bash
npm install pixi.js@~4.0.0 --save
```

which works great, but now webpack is warning that I'm including a minified file. Maybe I just don't know the magic to get webpack to shut up? Thanks for working on this awesome tool!

**Comment by dankreek** [comment]
Well shoot, I did some reading on peerDependencies and ended up putting a `noParse` section in my webpack config and everything's groovy!

**Comment by Izzimach** [comment]
Hm, I think if you build it from scratch that pixi.js and react get bundled in, but if you install it via `npm` that it actually references React and PIXI externally. The README should be updated to address that.

**Comment by dankreek** [comment]
Yeah, I wrote up that issue way too soon. I kind of dig the NPM way and it seems to be working flawlessly within the version ranges of PIXI and React specified.
