### ISSUE TITLE
Updating tilePosition of a TilingSprite

### ISSUE THREAD

**Issue by dankreek** [Izzimach/react-pixi#58]
I've found that I can create a new PIXI.Point and set it as the tilePosition of a `TilingSprite` but was wondering if you've thought about maybe making `tilePositionX`/`tilePositionY` properties to allow passing in simple integers as props? 

I'm definitely available to work on a PR if this is something you would be into.

**Comment by Izzimach** [comment]
Sure, I think you could just check for those props and then manually assign new values to the `PIXI.Point` held inside the `TilingSprite` instance.

I guess this is for rapidly changing x/y position for scrolling or something similar, to avoid creating a ton of `PIXI.Point` objects?

**Comment by dankreek** [comment]
Cool, started working on this last night. My current approach is parsing either a size-2 array as [x,y] or a comma-separated string "x,y". And yeah, the impetus is two-fold. I don't really want to create more objects than needed to in general but really it's mostly a syntax issue for me. I plan on eventually using this library in ClojureScript w/Reagent to do some game development. As a precursor to this, I'm toying with this lib in JS and working on a little parallax scroller demo, much like [the one I did](http://www.jmaythings.com/2016/03-21-parallax-scroller-pt1.html) with straight ClojureScript and PIXI

**Comment by dankreek** [comment]
Oh and as a quick explanation of why I went with that route: it will allow for a general case when assigning values to any prop that's a `PIXI.Point` or `PIXI.ObservablePoint`. You'll see when I get the PR up.

**Comment by Izzimach** [comment]
Yeah, I was actually going to suggest just allowing the user to enter an [x,y] array. Allowing arrays to appear anywhere a `PIXI.Point` appears would also make it easier to use `Vec2` objects from thi.ng

**Comment by dankreek** [comment]
@Izzimach I've got some docs and example code coming up tonight and we should be able to close this issue.

**Comment by dankreek** [comment]
And I'm wondering, should I maybe try using React's `propTypes` to guard against invalid input? Or is the current method sufficient? I'm a bit of a React noob.
