### ISSUE TITLE
Error when npm run build

### ISSUE THREAD

**Issue by nil84** [Izzimach/react-pixi#65]
:~/react-pixi# npm run build

> react-pixi@0.9.1 build /root/react-pixi
> webpack

Hash: 79ca3733e428f90106fa
Version: webpack 1.13.3
Time: 9832ms
        Asset     Size  Chunks             Chunk Names
react-pixi.js  1.42 MB       0  [emitted]  main
    + 271 hidden modules

WARNING in ./~/ify-loader!./~/pixi.js/bin/pixi.min.js
Critical dependencies:
8:412-419 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ify-loader!./~/pixi.js/bin/pixi.min.js 8:412-419

WARNING in ./~/pixi.js/bin/pixi.min.js
Critical dependencies:
8:412-419 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/pixi.js/bin/pixi.min.js 8:412-419

ERROR in ./src/ReactPIXI.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMultiChild' in /root/react-pixi/src
 @ ./src/ReactPIXI.js 45:23-59

ERROR in ./src/ReactPIXI.js
Module not found: Error: Cannot resolve module 'react/lib/ReactUpdates' in /root/react-pixi/src
 @ ./src/ReactPIXI.js 53:20-53

ERROR in ./src/ReactPIXIMonkeyPatch.js
Module not found: Error: Cannot resolve module 'react/lib/ReactCompositeComponent' in /root/react-pixi/src
 @ ./src/ReactPIXIMonkeyPatch.js 35:31-75

ERROR in ./src/ReactPIXIMonkeyPatch.js
Module not found: Error: Cannot resolve module 'react/lib/ReactReconciler' in /root/react-pixi/src
 @ ./src/ReactPIXIMonkeyPatch.js 39:23-59

ERROR in ./src/ReactPIXIMonkeyPatch.js
Module not found: Error: Cannot resolve module 'react/lib/shouldUpdateReactComponent' in /root/react-pixi/src
 @ ./src/ReactPIXIMonkeyPatch.js 43:34-81

**Comment by Izzimach** [comment]
Are you using React 15.4? This is probably the same problem seen for [react-three](https://github.com/Izzimach/react-three/issues/90).  The fix is probably [similar to this](https://github.com/Izzimach/react-three/commit/613105340e32a4fdf451f0811616ea7bd083320e)
