### ISSUE TITLE
Add support for rect

### ISSUE THREAD

**Issue by funkjunky** [Izzimach/react-pixi#73]
Perhaps I'm just not seeing it in the readme or examples. Is it possible to create a simple rect or arc?

I prefer to prototype games using shapes.

**Comment by Izzimach** [comment]
There is no `Rect` or `Arc` component in pixi so there isn't one in react-pixi.

You can try to do it use the `Graphics` component, [shown in this PR](https://github.com/Izzimach/react-pixi/pull/64)

**Comment by funkjunky** [comment]
oh ok, cool.

So hypothetically I could create an arc and rect component that uses the graphic component to draw an arc or rect and nest those in my application.

Ok, thanks for the link! You can close this for sure.

**Comment by funkjunky** [comment]
It lacks features, but I made a component for arc and rect:

```
import React from 'react';
import pixi from 'pixi.js';
import { Graphics } from 'react-pixi';

export class Rect extends React.Component {
    drawRect = ({ x, y, width, height, rotation }) => {
        this.refs.graphics.clear();
        this.refs.graphics.lineStyle(2, 0x0000FF, 1);
        this.refs.graphics.beginFill(0x0000FF, 1);
        this.refs.graphics.drawRect(0, 0, width, height);
        this.refs.graphics.endFill();
    }

    componentDidMount() {
        this.drawRect(this.props);
    }

    componentWillReceiveProps(props) {
        this.drawRect(props);
    }

    render() {
        return <Graphics ref='graphics' x={this.props.x} y={this.props.y}/>;
    }
}
```

Thanks again Izzimach.
