### ISSUE TITLE
How to handle animations.

### ISSUE THREAD

**Issue by funkjunky** [Izzimach/react-pixi#76]
I'm going to a game jam this weekend and plan to try and use react-pixi to make my game.

I think I've figured out a perfect storm of react, redux, sagas, with react-pixi to streamline development.

I haven't tried out animations yet, but I fear if I rapidly try and change the image attribute of a sprite component, it won't be smooth, because the image isn't a preloaded texture.

Is this a concern?
If it is, should I use the global pixi class to create the textures and feed that into the sprite component?

Is this the best way to do animations or is there another way?

**Comment by Izzimach** [comment]
I haven't done such a thing with pixi so I can't give you solid advice. I can say that using similar libs that I would either pre-load all the textures (complete with loading screen) or combine the textures into a single texture atlas and use that.

But you should also try just changing the image rapidly and see where it gets you. You might miss a few images at the start but once all the images are loaded and cached by the browser you should be able to switch image instantly without a problem.

**Comment by funkjunky** [comment]
Sorry for not closing this earlier.

Animations ran smoothly for me during the game jam. They were very simple though, so perhaps more complicated games would have a tougher time.

Regardless, as-is things worked great :)
