### ISSUE TITLE
Update pixi.js

### ISSUE THREAD

**Issue by gopchenkoalexey** [Izzimach/react-pixi#78]
Hello. Are you going go to update pixi.js dependency to the latest version?

**Comment by Izzimach** [comment]
It's already on pixi v4. Or do you mean pixi v4.4?

**Comment by neftaly** [comment]
Can the peerDep be changed from `~4.0.0` to `^4.0.0`?

**Comment by Izzimach** [comment]
Sure, in commit aeaddb02ccb3ebfcb17065b58ea5623efba5f5ea
