### ISSUE TITLE
pixi-display

### ISSUE THREAD

**Issue by kozlown** [Izzimach/react-pixi#82]
Hi, i'm trying to make layers with [pixi-display](https://github.com/pixijs/pixi-display) and react-pixi and I don't know if it's possible, could you enlighten me ?

**Comment by Izzimach** [comment]
I don't think that's going to work. It appears that pixi-display modifies several of the default classes such as `DisplayGroup` and `Container` so you would need to set up the code to apply those changes and then properly access them through props. 

To produce something similar you could order the children in the order you want them drawn.  This isn't perfect but it should let you control the ordering of sprite drawing.
