### ISSUE TITLE
Render null breaks

### ISSUE THREAD

**Issue by EloB** [Izzimach/react-pixi#85]
Hello

I have so problems with render `null` as the root element of a component. Getting this error "Uncaught (in promise) TypeError: Cannot read property '_idCounter' of undefined". In this case I can't change the logic because it's inside an HOC of recompose (https://github.com/acdlite/recompose).

```
Uncaught (in promise) TypeError: Cannot read property '_idCounter' of undefined
    at ReactDOMEmptyComponent.mountComponent (eval at <anonymous> (index.js:8231), <anonymous>:29:34)
    at Object.mountComponent (eval at <anonymous> (index.js:1539), <anonymous>:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (eval at <anonymous> (index.js:3894), <anonymous>:371:34)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (index.js:3894), <anonymous>:258:21)
    at Object.mountComponent (eval at <anonymous> (index.js:1539), <anonymous>:46:35)
    at Object.mountChildren (eval at <anonymous> (index.js:3990), <anonymous>:238:44)
    at Object.mountAndAddChildren (eval at <anonymous> (index.js:8866), <anonymous>:366:31)
    at ReactReconcileTransaction.perform (eval at <anonymous> (index.js:2087), <anonymous>:140:20)
    at Object.componentDidMount (eval at <anonymous> (index.js:8866), <anonymous>:469:18)
    at eval (eval at <anonymous> (index.js:3894), <anonymous>:265:25)
```

This also triggers the issue.
```js
class Delayed extends Component {
  state = { ready: false };
  componentDidMount() {
    setTimeout(() => this.setState({ ready }, 1000);
  }
  render() {
    return !this.state.ready ? null : <Text />;
  }
}
```

Also broken.
```
const StatlessComponent = ({ value }) => {
  if (!value) return null;
  return <Text text={value} />
};
```

**Comment by EloB** [comment]
Also crashes when you swap root element.

```js
const one = <Text text="One" />;
const two = <DisplayObjectContainer />;
class Test extends Component {
  state = { one: true };
  componentDidMount() {
    setInterval(() => this.setState({ one: !this.state.one }), 3000);
  }
  render() {
    return this.state.one ? one : two;
  }
}
```

**Comment by EloB** [comment]
@Izzimach I know that you do this on your spare time. I'm in the making of chosing which way I want to go now for a private project. I would love to use your pixi renderer. Do you have any estimates when this could be fixed?

**Comment by Izzimach** [comment]
Fixing this probably involves looking at some React internals so I don't know exactly what the problem is. I can look at it on Tuesday and see what's going on but I can't get any more specific than that, sorry.

**Comment by EloB** [comment]
@Izzimach I would love you if you could take a look at it. I really want Pixi for my stuffs. I'm developing for devices with poor performance and DOM is not what I would like to use :)

**Comment by Izzimach** [comment]
These may fix the problem:

9fed0ff33ede0f04a089fe2416c2de075b0ba739
8c185e5070d41d94a3a23ab7d6af005ec39dbf12

 This change the default null element to a PIXI DisplayObject. You won't be able to render null DOM elements at the same time because of this. Getting two renderers to properly render null is a big mess.

**Comment by EloB** [comment]
Will you look into the mess later or is this a dead end?

**Comment by Izzimach** [comment]
React assumes there is only one renderer so to support two different Empty component types I would have to rewrite several parts of React myself, which is not practical.

You might be able to import two versions of React --- `react-dom` and `ReactPIXI` and use them side-by-side, but you can't embed PIXI inside of a React DOM tree. Sorry if that's what you had planned. Have you looked at using SVG elements? They should provide much of the same functionality.

**Comment by michalochman** [comment]
@Izzimach can you please revert the [EmptyComponent injection](https://github.com/Izzimach/react-pixi/blob/master/src/ReactPIXI.js#L935-L937) you have implemented in 9fed0ff?

I think it's better to make react-pixi users return `DisplayObjectContainer` instead of `null` than to break any null returns in all the other react libraries using react-dom.

**Comment by EloB** [comment]
I don't think that is a good idea. It's a common way to hide something. The problem will be that hoc's want work. For instance `recompose`.

**Comment by Izzimach** [comment]
It's pretty broken either way. React wasn't really built to handle situations like this.

If you don't feel like loading multiple copies of React (one for `react-dom` and one for `react-pixi`) then maybe there could be a separate function to call to revert to the old `null` behavior.

**Comment by michalochman** [comment]
@EloB the problem is that this inject breaks all `return null` in ReactDOM world. This should only work this way for react-pixi and should not break react-dom renderer.

@Izzimach what are your ideas on loading separate copies of react?

**Comment by Izzimach** [comment]
At one point you could configure webpack to build react-pixi with its own internal copy of React, separated from the 'default' instance of React. It caused some problems and I don't know if running multiple instances of React still works - I saw some error checking code inside of the React library regarding that.

The best I can offer is some call to control the EmptyComponent injection. Trying to auto-detect whether a `null` is in DOM-land or PIXI-land is either hard or impossible,

**Comment by michalochman** [comment]
I was looking at how `ReactDOMEmptyComponent` is implemented and then playing around with `ReactPIXI.js` file I found that it is somewhat possible to detect this by importing:

```javascript
+import ReactDOMComponent from 'react-dom/lib/ReactDOMComponent'
+import DOMLazyTree from 'react-dom/lib/DOMLazyTree'
```

and then adding the below in `NullDisplayObject.mountComponent`, before the `return` statement:
```javascript
+      // taken from ReactDOMEmptyComponent.prototype.mountComponent, but without ReactDOMComponentTree.precacheNode call
+      if (this._nativeParent instanceof ReactDOMComponent) {
+        var nodeValue = ' react-empty: ' + this._nativeContainerInfo._idCounter++ + ' ';
+        var ownerDocument = nativeContainerInfo._ownerDocument;
+        var node = ownerDocument.createComment(nodeValue);
+        return DOMLazyTree(node);
+      }
+
```

This worked for mounting `null`, but there were some issues I was not able to trace yet, while unmounting, when the  `removeChild` method was called:

`Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`

Any thoughts?

**Comment by michalochman** [comment]
@Izzimach I was finally able to fix this.

Looks like the development mode of React required some internal attributes to be set, like `_hostNode`, thus I have made it fully compatible with what `ReactDOMEmptyComponent` does.
