### ISSUE TITLE
None of the examples are working

### ISSUE THREAD

**Issue by chucksellick** [Izzimach/react-pixi#88]
I clone the repository then run the examples with:

npm install
npm run examples

Everything appears to install and build fine with no errors. But when I go to localhost:8080 and click on any of the examples I get a black screen and a load of console errors, e.g. this is for spinningsprite.html:

![image](https://user-images.githubusercontent.com/1188786/28295193-f44dde16-6b56-11e7-9ebf-7cba8967ec41.png)

Node version is v8.1.4. Wondering if this could be the issue.

**Comment by Izzimach** [comment]
This looks like some weirdness in pixi.js code v4.5.* related to marking deprecated properties. Until I figure out what's going on, you can `npm install pixi.js@4.4`

**Comment by chucksellick** [comment]
This gets stranger ... using pixi.js 4.4.4 got rid of the errors but I'm still just seeing a black screen on all examples unfortunately. I've done some breakpointing and can confirm that the components are generating sprites and calling .renderStage() ... but still nothing is rendering. Any ideas?

**Comment by Izzimach** [comment]
Yeah, it appears that `stage.render()` is getting called but nothing is showing up.

Not sure what's going on. Maybe pixi won't work unless it's built with [pixify](https://github.com/pixijs/pixify)? There were some previous problems with glslify and such as well.

**Comment by Izzimach** [comment]
It appears that PIXI deprecation get double-called due to the `expose` require in `react-pixi-exposeglobals.js`. Since PIXI dumps itself into globals by default, this can safely be nuked without requiring code changes.

**Comment by chucksellick** [comment]
Great, thanks for really quick response :)
