### ISSUE TITLE
StagePropsType doesn't exhaustively contain renderer properties

### ISSUE THREAD

**Issue by kjin** [Izzimach/react-pixi#93]
The TS type definitions for `StagePropsType` don't include properties accepted in [generateDefaultRenderer](https://github.com/Izzimach/react-pixi/blob/568f177e4ca011a513e7d80dac4c63783c3d14ab/src/ReactPIXI.js#L365), so the TS compiler emits errors if I try to, for example, set the background color of a stage.

I'd be happy to contribute a fix -- though I'm not sure whether I should directly modify the TS definition template, or try to include it in `generateDeclaration.ts`; the issue being that `Stage` doesn't have a corresponding class in PIXI like the other auto-generated components do.

**Comment by kjin** [comment]
Oops... just saw #83. What's the status on that PR?

**Comment by Izzimach** [comment]
I merged #91 but wasn't sure if that conflicted with #83. Looking at it, I think there is no overlap there, right? I don't use Typescript so I can't really check if it's working. I can merge #83 as well if you think that looks safe.

**Comment by kjin** [comment]
It seems to work for me.

**Comment by Narazaka** [comment]
I also think there is no issues.

**Comment by Izzimach** [comment]
OK, merged in #83 as well
