### ISSUE TITLE
ReactPIXI.Text doesn't update its style prop

### ISSUE THREAD

**Issue by a-rasinski** [Izzimach/react-pixi#99]
Style property is only set when Text component is mounted.

Introduced [here](https://github.com/Izzimach/react-pixi/commit/66b88324967cf5e3577502f5b395df7532dfdf4f). It should assign to `displayObject.style` attribute.

**Comment by a-rasinski** [comment]
@Izzimach Hi, is there any chance for a released version with this bug fixed? I'd really appreciate if you did.

**Comment by Izzimach** [comment]
Was this not fixed in 0.9.15? That was pushed after this commit.

**Comment by a-rasinski** [comment]
My bad sir! I checked tags list and the latest there was 0.9.14.
Thank you very much!
